version: "2"
run:
  go: "1.24"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    revive:
      severity: error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
