run:
  go: "1.21"
  deadline: 10m
  allow-parallel-runners: true
linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Optional linters
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - gosec
    - misspell
    - noctx
    - nolintlint
    - revive
    - stylecheck
    - whitespace
linters-settings:
  revive:
    ignore-generated-header: true
    severity: error
